
# Typo check: https://github.com/crate-ci/typos

[files]
extend-exclude = ["go.sum", "*.js", "*.css", "*.html"]

[default.extend-identifiers]
# *sigh* this just isn't worth the cost of fixing
Collison = "Collison"